#+TITLE: Abstract
#+TOC: nil
The goal of the project is to compare different data-driven models for the behavior of zebrafish.
The models should be able to predict and simulate the individual motion of an animal reacting to its environment (e.g. another fish, wall).
It can be used to steer a fish in a virtual reality environment, for example.

We start with the evaluation of a simple force based model.
The model consists of two parts, one that models the information processing and one that models the gliding phase.
The gliding is described by a physical model with parameters taken from the data.

We will then enhance the model by using a spatio-temporal (linear) receptive field as the social model that includes information about the perception of the fish.
This modeling strategy is inspired by computational neuroscience and adds a 'memory' to the model.

As a next step, the receptive field will be replaced by a recurrent neural network.
This is a generalization of the previous model and includes possible non-linear reactions and time-dependencies.
